plotly/falcon

- api.js
- app/actions/ipc.js
- app/components/Settings/ConnectButton/ConnectButton.react.js
- app/components/Settings/Preview/Preview.react.js
- app/components/Settings/Settings.react.js
- errors.js
- main.development.js
- messageHandler.js
- sequelizeManager.js
- test/e2e.js
`/v1/connect`
response:
```
{
error: null
}
```
`/v1/databases`
response:
```
{
databases: [
"information_schema",
"mysql",
"performance_schema",
"sys",
"testdb"
],
error: null
}
```
`/v1/selectdatabase?database=testdb`
response:
```
{
error: null,
connectionCode: "200"
}
```
`/v1/selectdatabase?bleep=blop` or `/v1/selectdatabase`
response:
```
{
error: {
mesasge: "No database entry found. Please provide a database entry such as '/endpoint?  database=database_name",
timestamp: "11:54:53 GMT-0400 (EDT)"
}
}
```
`/v1/tables`
response:
```
{
error: null,
tables: [
{
consumercomplaints: { }
},
{
test: { }
}
]
}
```
`/v1/preview?tables=testdb`
response:
```
{
error: null,
previews: [
{
test: {
columnnames: [
"firstColumn",
"secondColumn",
"thirdColumn"
],
ncols: 3,
nrows: 5,
rows: [
[
1,
1, …
```
> Api versioning

- app/actions/ipc.js
- app/app.global.css
- app/components/Settings/ConnectButton/ConnectButton.react.js
- app/components/Settings/DatabaseDropdown/DatabaseDropdown.css
- app/components/Settings/Logger/Logger.css
- app/components/Settings/Logger/Logger.react.js
- app/components/Settings/Preview/Preview.react.js
- app/components/Settings/Settings.css
- app/components/Settings/Settings.react.js
- app/components/Settings/TableDropdown/TableDropdown.css
- app/components/Settings/TableDropdown/TableDropdown.react.js
- app/components/Settings/TableDropdown/react-select.css
- app/reducers/ipc.js
- test/e2e.js
UI:
tableDropdown and change scrollbar
> Table dropdown

- package.json
- webpack.config.base.js
> bunyan has to be an external dep

- app/components/Settings/Logger/Logger.react.js
- app/components/Settings/Settings.react.js
- backend/acceptedDomains.yaml
- backend/api.js
- backend/main.development.js
- backend/routes.js
- backend/setupServers.js
> Post requests

- backend/main.development.js
- Unify help menu item across windows and mac
- Fix help links
cc @alexandresobolevski
> Update menu itmes

- app/components/Settings/Settings.react.js
> [UI] Adds video explaining unsafe scripts

- app/actions/sessions.js
- app/components/SessionsManager/SessionsManager.css
- app/components/SessionsManager/SessionsManager.react.js
- backend/args.js
- backend/messageHandler.js
- backend/setupServers.js
- test/e2e.js
can already be modified in `acceptedDomains.yaml` but now UI option as well!
#88 
here I start an on-prem session with a domain www.google.ca which then accepts requests from that domain but not from www.yahoo.com
> [FEAUTURE] on-prem domain can be added by UI

- app/actions/sessions.js
- app/components/SessionsManager/SessionsManager.react.js
- app/reducers/sessions.js
- backend/api.js
- backend/errors.js
- backend/messageHandler.js
- backend/routes.js
- backend/sequelizeManager.js
- test/e2e.js
/sessions
/deletesession
/addsession
> Sessions api

- app/components/Settings/Settings.react.js
- app/utils/utils.js
@alexandresobolevski - could you review? a couple different things here, check it out commit-by-commit
> Rm https section

- app/components/Settings/UserConnections/UserConnections.react.js
- backend/persistent/Connections.js
- backend/routes.js
- test/backend/routes.spec.js
- don’t return them in any of the api calls
- don’t display them in plain text
> treat s3 access keys like passwords

- backend/parse.js
- test/backend/Datastores.spec.js
- test/backend/utils.js
Also replace the slow `.map` calls with faster `for` loops.
Tests coming up
> JSON stringify objects

- app/oauth/index.js
visiting this URL gives a pretty scary message
> help docs are http not https

- app/actions/sessions.js
- app/components/Settings/HttpsServer/DetectCertificates.react.js
- app/oauth/index.js
- app/utils/https.js
PR against 2.1.0 branch for a maintenance release.
Tested the solution by fetching from the browser. The failing and successful case was replicated. 
https://github.com/plotly/streambed/issues/9142
> Include credentials in all front-end fetch requests.

- .eslintrc
- app/components/Settings/UserConnections/UserConnections.css
- app/components/Settings/UserConnections/UserConnections.react.js
- app/constants/constants.js
- backend/persistent/datastores/Sql.js
- test/backend/Datastores.spec.js
required a little refactoring of the user inputs form and css.
fixes https://github.com/plotly/plotly-database-connector/issues/142
> Mssql timeout

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- package.json
Hey there! This is a general documentation audit. I've changed a few things:
- Added a Code of Conduct. This is the same one used on ropensci/plotly. 
- Added a link to Github in the bugs and homepage field in the package.json.
- Edited the headers on contributing and readme files (mostly depth).
- Added 2017 to the license year.
> Developer Experience Audit

- app/login/index.js
cc @chriddyp  cause all the other Plotlys on this page are capitalized ![screen shot 2017-05-30 at 3 47 37 pm](https://cloud.githubusercontent.com/assets/2789078/26601938/d3125416-454f-11e7-8307-7fbdb1f38e59.png)
> cap plotly

- app/constants/constants.js
- sample-storage/connections.yaml
- test/backend/datastores.livy.spec.js
This PR updates all the references of spark test database to a newer/stable version.
> Update spark test db IP

- app/components/Configuration.react.js
- app/components/Settings/Preview/ApacheDrillPreview.js
- app/components/Settings/Preview/ChartEditor.react.js
- app/components/Settings/Preview/components/AxisDropZone.react.js
- app/components/Settings/Preview/components/Box.react.js
- app/utils/utils.js
@chriddyp the whole code in `app` mainly throws [no-unused-vars]() and [react/prop-types] errors. I think it'd be a good idea to let you review a few commits before continuing. Let me know if you prefer less granular commits.
> Eslint fixes in app

- test/backend/Connections.spec.js
- test/backend/Datastores.spec.js
- test/backend/PlotlyAPI.spec.js
- test/backend/QueryScheduler.spec.js
- test/backend/certificates.spec.js
- test/backend/datastores.impala.spec.js
- test/backend/datastores.livy.spec.js
- test/backend/routes.spec.js
- test/backend/settings.spec.js
- test/backend/utils.js
- test/integration_test.js
Please take special note about changes in `test/backend/routes.spec.js`: 
1) I've extracted a method to clean up settings (via unlinkSync)
2) I've noticed a couple of `res.json()` calls that seem obsolete to me, please see the respective `TODO` in line 329
> Eslint fixes in tests

- app/components/Settings/Settings.react.js
- circle.yml
- Mostly fix `react/prop-types` and `no-unused` problems
> Fix a huge pile of ESLint problems in Settings component

- .eslintrc
- app/components/Configuration.react.js
- app/components/Oauth.react.js
- app/components/Settings/Preview/components/editorConstants.js
- app/constants/constants.js
- package.js
- package.json
- scripts/install-modules.js
- webpack.config.production.js
- webpack.config.web.js
@chriddyp these were the last ESLint problems in the code base. I thought activating the `no-trailing-spaces` rule would be nice, so I did. In case we don't need it, let's just discard the commit.
> Eslint remaining fixes

- backend/routes.js
- package.json
- test/backend/routes.spec.js
@chriddyp my proposal to enable ESLint. Afai understand form my limited research, CircleCI is about testing and Travis and AppVeyor are about creating builds. 
**Update:** ESLint resulting in no problems won't produce any output whatsoever, just in case someone might wonder if ESLint really ran.
> Eslint enable in tests

- app/components/Settings/Settings.react.js
- app/index.js
- app/utils/utils.js
- backend/persistent/datastores/Sql.js
* also removed a noisy console warning
* and fixed all the lint warnings
> Redshift: fix query to retrieve table schemas

- app/components/Login.react.js
- app/index.js
- backend/routes.js
- static/index.html
- static/oauth.html
- test/backend/routes.spec.js
Reverts oauth2 callback url to `/oauth2/callback`. This fixes Backward incompatibility
introduced in v2.3.2
> Revert Oauth2 callback url.

- app/components/Oauth.react.js
- backend/plugins/authorization.js
- backend/utils/authUtils.js
Updates Oauth issue mentioned in #227
> Update oauth token-save url

- backend/persistent/QueryScheduler.js
* Ensure the scheduler doesn't run a query if the previous run hasn't completed.
* Fixed MaxListenersExceededWarning seen while running `QueryScheduler.spec.js`.
> Fix race in QueryScheduler

- app/components/Settings/UserConnections/UserConnections.react.js
Fixes https://github.com/plotly/falcon-sql-client/issues/241
@n-riesco or @tarzzz - could you review?
cc @johnmyleswhite - thanks for reporting!
> Add more extension options for sqlite

- backend/plugins/authorization.js
- backend/utils/authUtils.js
@n-riesco What we discussed on slack.. 
This is needed for fixing on-prem authentication.
> Fix authentication

- backend/certificates.js
Fixes many of the console warnings displayed during testing.
> certificates: fix uncaught promise rejection

- circle.yml
CircleCI 2 support, thanks to the CircleCI team member @ryanwohara
Builds are 5 minutes faster now (14 min vs 19 min) 🚀
> CircleCI 2!

- test/backend/routes.spec.js
> test: more verbose log on oauth failure

- app/components/Settings/Preview/components/getPlotJsonFromState.js
- app/components/Settings/UserConnections/UserConnections.react.js
- backend/persistent/datastores/Sql.js
- test/backend/routes.spec.js
- webpack.config.electron.js
- webpack.config.headless.js
* Fixes sqlite file selector in windows and linux.
* Fixes sqlite schema preview.
* Fixes a few linting warnings.
Closes #280
> Fix sqlite connector

- Dockerfile
> Dockerfile: pin node and yarn to major version

- app/actions/sessions.js
- app/components/Settings/Preview/Preview.react.js
- app/components/Settings/Settings.react.js
- app/constants/constants.js
> editor: use preview query as default query

- app/components/Settings/Preview/TableTree.react.js
> sqlite: create a database label for preview

- app/components/Login.react.js
- package.json
> Login Screen Updates 

- app/components/Settings/Preview/Preview.react.js
- app/components/Settings/Settings.react.js
- backend/persistent/PlotlyAPI.js
- backend/routes.js
> Fix Export links for on-premise

- Dockerfile
- app/components/Configuration.react.js
- app/components/Login.react.js
- backend/routes.js
- webpack.config.web.js
> Use env var for auth frontend

- backend/persistent/PlotlyAPI.js
@n-riesco Please review.. cc: @scjody 
@n-riesco Please let me know if this is the right branch to merge into.
Fixes https://github.com/plotly/streambed/issues/10466
> Check user exist before adding authorization header

- backend/settings.js
- circle.yml
- sample-storage/connections.yaml
- test/backend/datastores.ibmdb.spec.js
- test/backend/datastores.livy.spec.js
- test/backend/utils.js
- test/docker/README.md
- test/docker/deployment/db2-deployment.yaml
- test/docker/deployment/db2-service.yaml
- test/docker/deployment/impala-deployment.yaml
- test/docker/deployment/impala-service.yaml
- test/docker/deployment/spark-deployment.yaml
- test/docker/deployment/spark-service.yaml
- test/docker/spark/Dockerfile
Part of https://github.com/plotly/streambed/issues/10022
> Added GKE configs for test databases

- backend/persistent/datastores/dataworld.js
- test/backend/datastores.dataworld.spec.js
> dataworld: fix typo

- backend/persistent/datastores/datastoremock.js
- test/backend/datastores.ibmdb.spec.js
- test/backend/datastores.livy.spec.js
- test/backend/datastores.mock.spec.js
This PR covers some custom mock results for queries, which are used in testing Falcon against Workspace `sql_panel`.
> Added custom mock results

- circle.yml
> circle: reset cache

- circle.yml
* Show node and yarn versions to help debug issues due to versions.
@tarzzz could you do the review, please?
> circleci: show node and yarn versions

- README.md
> README.md: add list of maintianers

- README.md
@jackparmer Good  news! [I've asked @shannonlal](https://github.com/plotly/falcon-sql-client/pull/352#issuecomment-362903033) to join the team of maintainers.
> README: add Shannon Lal to list of maintainers

- backend/plugins/authorization.js
- backend/routes.js
> oauth: check status code before parsing body

- backend/persistent/PlotlyAPI.js
- package.json
- test/backend/PlotlyAPI.spec.js
@shannonlal I'd like to use this PR to show you two of the helper functions we use in the specs (`assertResponseStatus` and `getResponseJson`). Would  you like to review this PR?
When we review a PR, we have the convention of using 💃 to indicate the points raised by the review have been addressed and the PR is ready to merge.
> test: check status code in specs for PlotlyAPI

- package.json
- test/backend/PlotlyAPI.spec.js
- test/backend/QueryScheduler.spec.js
- test/backend/certificates.spec.js
- test/backend/datastores.dataworld.spec.js
- test/backend/datastores.elasticsearch-v2.spec.js
- test/backend/datastores.elasticsearch-v5.spec.js
- test/backend/datastores.elasticsearch.spec.js
- yarn.lock
* Fixed failures in CircleCI caused by `chai-spies`.
* I tried to use sinon-chai but it throws the same error as chai-spies.
Fixes #373 
---
@tarzzz would you review this PR?
> test: replace chai-spies with sinon

- backend/persistent/datastores/Elasticsearch.js
> Rebased PR #370 agains current master

- backend/persistent/PlotlyAPI.js
> PlotlyAPI: use res.text() if request failed

- app/components/Settings/Settings.react.js
cc/ @tarzzz @scjody 
Closes https://github.com/plotly/streambed/issues/10695
> onprem: warn onprem users about shared connections

- README.md
@jackparmer Good news! @kndungu wants to join the team of maintainers.
> README: add Kinuthia Ndung'u to maintainers list

- CHANGELOG.md
- LICENSE
- package.json
> Version 2.6.0

- app/components/Settings/Preview/TableTree.react.js
> schemas: show vertical scrollbar if needed

- CHANGELOG.md
- package.json
> Version 2.8.0

- app/components/Settings/scheduler/preview-modal.jsx
> Fix overflow for Preview modal

- CHANGELOG.md
- package.json
> Version 3.0.0

- app/components/Settings/Settings.react.js
Closes https://github.com/plotly/streambed/issues/11288
> Fix on-prem login link for login modal

- backend/persistent/datastores/oracle.js
Ability to query across schemas with the Oracle connector
> Cross-schema Oracle patch

- app/components/Settings/DialectSelector/DialectSelector.react.js
- app/components/Settings/Settings.react.js
- app/components/Settings/scheduler/modals/create-modal/create-modal.jsx
- app/components/Settings/scheduler/modals/preview-modal.jsx
- app/components/Settings/scheduler/presentational/api-call-counts.jsx
- app/components/Settings/scheduler/presentational/timestamp.jsx
- app/components/Settings/scheduler/scheduler.css
- app/components/Settings/scheduler/scheduler.jsx
- app/utils/queryUtils.js
- backend/persistent/QueryScheduler.js
- backend/routes.js
- static/css/DialectSelector.css
- static/css/Settings.css
- test/app/components/Settings/DialectSelector/DialectSelector.test.js
- test/app/components/Settings/scheduler/create-modal.test.jsx
- test/app/components/Settings/scheduler/preview-modal.test.jsx
- test/app/components/Settings/scheduler/scheduler.test.jsx
- test/backend/QueryScheduler.spec.js
- test/backend/routes.queries.spec.js
This PR adds two features: 
- UI elements to notify the user about API call limits as well as where they stand with regard to the limits
- Refactors connection selection UI into a dropdown instead of selecting one of many static logos
closes #519
> API call counts and dropdown connection select

- app/constants/constants.js
(Help prevent invalid security reports about these credentials being disclosed.)
@nicolaskruchten Please review.
> Add note re: sample credentials
