plotly/falcon

- app/components/Settings/TableDropdown/TableDropdown.react.js
resolves #80 
added a check for length of tables' array.
displays 'select a database' if null, dispplays 'none' if tables received and array is empty
> [ISSUE] Resolves error trying rendering the dropdown options when tables array is empty

- app/components/Settings/ConnectButton/ConnectButton.css
- app/components/Settings/UserCredentials/UserCredentials.css
- app/components/Settings/UserCredentials/UserCredentials.react.js
- app/constants/constants.js
- backend/sequelizeManager.js
- test/e2e.js
adds the option `ssl` to the UI as a database option
as in if ssl is used by the remote database (certificates have been setup)
can remain undefined for most databases except redshift
- from now on, it's defaulted to `false` and can be overwritten by the user using the checkbox
- for reshift it's defaulted to true always
> Add database options ui

- app/components/Settings/ConnectButton/ConnectButton.react.js
- app/components/Settings/Settings.react.js
I made it cleaner.
Bug was in the fact that the 'loading' state was inside saveConnectionRequest and not connectRequest as checked in this component.
> Better handle loading state

- app/components/Settings/UserConnections/UserConnections.react.js
Clicking on the documentation is broken on the web build right now. Also, I don't think that we even have valid links for all of the dialects any more (elasticsearch, s3, apache drill)
> Remove documentation setting

- backend/routes.js
After including credentials in the streambed client side requests to connector's server:
> Fetch API cannot load https://plotly-connector.herokuapp.com/connections. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'https://local.plot.ly' is therefore not allowed access.
> Accept credentials header serverside

- backend/certificates.js
- test/backend/PlotlyAPI.spec.js
- test/backend/utils.js
This PR restores the updateGrid test (previously skipped in order to merge #163).
This PR is merged on to top of #171.
> Fix intermittent failures in updateGrid test

- package.json
- yarn.lock
* Versions 2.2.1 fixes bug that prevented rebuilding the native package.
* See details in https://github.com/ibmdb/node-ibm_db/issues/313 .
> ibmdb: bump to version 2.2.1

- package.js
Fixes the broken mac builds, which were being caused by: https://github.com/ibmdb/node-ibm_db/issues/329
This is a workaround, and can be removed once the issue is resolved on `node-ibm_db` side..
> Added workaround for ibm_db2 issue

- app/components/Settings/UserConnections/UserConnections.react.js
- app/constants/constants.js
- backend/persistent/datastores/Sql.js
- package.json
- test/backend/utils.js
cc @BRONSOLO @tarzzz @charleyferrari 
these options might fix some issues that a client is having in connecting to their mssql instance
> add `instanceName` and `encrypt` options for mssql

- package.json
- yarn.lock
- Note: 'prop-types' was a transitive dependency and thus is
being used in a couple of places already. This commit makes the dependency an ordinary project dependency since `PropTypes` are at the core of React apps
- Is related to fixing a lot of ESLint `react/prop-types` errors
> Add dependency on 'prop-types' library

- sample-storage/connections.yaml
* Added comment to `connections.yaml` to describe that these credentials
are made public intentionally only for the purpose of testing
falcon-sql-connector.
> test: add comment to connections.yaml

- app/actions/sessions.js
If the postgres database contained tables whose names contained uppercase letters, then an error would appear in the UI and prevent the user from making further queries.
Example a table named Dogs would result in the error:
`relation "dogs" does not exist`
> Fix postgres PREVIEW_QUERY

- package.json
I find inconvenient to pin to a single node version.
@chriddyp Shall we pin only to the major number?
> package.json: pin engines to major number only

- test/backend/QueryScheduler.spec.js
* Increase refresh interval from 30 to 60 seconds.
* The spec 'QueryScheduler queries a database and updates a plotly grid
on an interval' fails if PlotlyAPIRequest takes longer than the
refresh interval to respond.
Closes #262
> test: increase refresh interval in QueryScheduler

- package.json
* Otherwise, windows app will fail to load ibm_db native module.
> electron-builder: disable asar

- .travis.yml
* Reduced artifact file size from 280MB to 94MB
> travis: zip only the mac installer

- test/backend/QueryScheduler.spec.js
- test/backend/routes.spec.js
- test/backend/utils.js
* If a response status assertion fails or a response body can't be
parsed as JSON, then ensure the response status and body are included
in the error message.
Closes #269
Closes #275
Closes #276
> test: improve error messages

- CONTRIBUTING.md
- package.json
* `yarn run docker:falcon:build` builds the Dockerfile and tags the image
as `falcon-sql-client:local`.
* `PLOTLY_CONNECTOR_AUTH_ENABLED=false yarn run docker:falcon:start`
runs `yarn run start-headless` inside a Docker container.
* Updated documentation in `CONTRIBUTING.md`.
> add scripts to build and run Dockerfile

- CONTRIBUTING.md
Updated the documentation for how to run the server build from source.  This is a fix for #307 and based on the documentation provided by @n-riesco.  I have tested the install instructions on Mac and they work.
> Fix for Install and Running Server

- app/index.js
I can now see that updating `package.json` in the onprem branch is going to waste our time.
Let's just remove the version when falcon runs onprem.
I've tested this commit locally. Could any of you test it on prem, please?
cc/ @scjody @tarzzz @chriddyp 
Closes https://github.com/plotly/streambed/issues/10450
> onprem: remove version from app title

- app/constants/constants.js
* Do not throw if preview query hasn't been defined for a connector.
Closes https://github.com/plotly/streambed/issues/10453
> app: set preview query for non-sql connectors

- package.json
* I had to disable asar in the package for Windows, because it breaks
ibm_db.
* Re-enable compression in packages for Linux
> pack: disable asar only in windows package

- app/components/Settings/Preview/Preview.react.js
Modifies `Preview.react.js` to show the time took by the query to run, in the same message as the `<n> rows retrieved`.
> Show query time along with "n rows retrieved".

- test/backend/routes.spec.js
The order of the rows returned by the redshift test server has changed.
Fixes failure in CircleCI
@chriddyp @tarzzz quick one for review
> test: update redshift tests

- app/actions/sessions.js
- app/components/Settings/Preview/Preview.react.js
- app/components/Settings/Settings.react.js
- app/constants/constants.js
* Fix invocation of `PREVIEW_QUERY` from `Settings.react.js` and
`Preview.react.js`. This fixes the initial preview query that depend
on the database name (e.g. MSSql).
---
@tarzzz Would you review this PR?
cc/ @shannonlal I thought you may want to have a look at this PR, since it touches code that affects the ElasticSearch connector.
> app: fix initial preview query

- app/components/Settings/Settings.react.js
* Wait for selectedTable before opening the Query tab.
Fixes #372
> Settings: wait for selectedTable

- backend/persistent/PlotlyAPI.js
This is so we can track anonymous chart and dataset exports coming from Falcon versus other tools using the Datacache API (Vernier etc)
> Add 'origin' key to Datacache form

- app/components/Settings/Preview/Preview.react.js
- backend/persistent/datastores/dataworld.js
- static/css/Preview.css
@kndungu @rflprr Since you are familiar with the code, would you like to review this PR?
* data.world: send error message of failed queries.
* Preview: repect line breaks in error messages and use mono-space font.
Closes #389
> dataworld: improve error message

- .gitignore
- backend/persistent/PlotlyAPI.js
- backend/routes.js
- test/backend/routes.spec.js
* Closes #397 (use of `res.json()` before checking `res.status`)
* Closes #398 (row order changed again in redshift test)
@tarzzz would you be able to review this PR, please?
> Closes #397 and #398

- circle.yml
* Tests in latest docker image circleci/node:6.13.1-browsers fail with
error:
/home/circleci/falcon/node_modules/electron/dist/electron:
error while loading shared libraries:
libgconf-2.so.4:
cannot open shared object file:
No such file or directory
> circle: pin to node@6.13.0

- app/components/Settings/Settings.react.js
* This commit is a workaround that fixes the breakage of the Query panel
triggered when switching back to a connection where the ChartEditor
was visible.
* It works around the breakage by hiding the ChartEditor and showing the
CodeEditor whenever the user clicks on a connection tab.
> Settings: hide chart & show code editor if needed

- backend/main.development.js
- backend/routes.js
Fixes plotly/streambed#10963
Closes #433
> Prevent navigation out of initial origin

- app/components/Settings/Preview/Preview.react.js
- app/components/Settings/Preview/code-editor.css
- app/components/Settings/Settings.react.js
cc/ @jackparmer 
Closes #443 
---
This PR also includes two bug fixes:
* fixes hidden run button (when auto-resize wouldn't be trigerred)
* ensures the schemas panel is shown when coming back to the query panel.
> Do not hide the code editor automatically

- app/components/Settings/Settings.react.js
@tarzzz could you review this PR, please?
---
The Plot.ly panel provides a link for users to log in and out of Plotly.
Unfortunately, the login link is hidden if the backend is able to launch the HTTPS server.
This PR ensures the login/logout link is always shown, regardless of the backend.
---
Before this PR
---
With this PR
> settings: ensure login link is visible

- app/components/Settings/Settings.react.js
@shannonlal I've added a comment to explain the reason why `scheduledQuery` is set to `null`. I want to check the explanation makes sense to everybody· Please, could you read it and see if it needs rewording?
> scheduler: document reason to unset scheduledQuery

- backend/routes.js
* Mitigation measure against clickjacking.
Closes https://github.com/plotly/streambed/issues/11103
cc/ @tarzzz @scjody @nicolaskruchten @kndungu
> routes: set X-Frame-Options: DENY

- app/actions/sessions.js
- app/components/Settings/scheduler/create-modal.jsx
- app/components/Settings/scheduler/preview-modal.jsx
- app/components/Settings/scheduler/request-error.jsx
- app/constants/constants.js
- backend/persistent/QueryScheduler.js
- backend/persistent/plotly-api.js
- backend/routes.js
- backend/utils/cronUtils.js
- test/app/components/Settings/scheduler/create-modal.test.jsx
- test/app/components/Settings/scheduler/preview-modal.jsx
> [WIP] upload scheduled query metadata

- app/actions/sessions.js
- app/components/Settings/scheduler/create-modal.jsx
- app/components/Settings/scheduler/preview-modal.jsx
- app/components/success.jsx
- app/utils/utils.js
- backend/persistent/QueryScheduler.js
- backend/persistent/plotly-api.js
- backend/routes.js
- backend/utils/gridUtils.js
- test/app/components/Settings/scheduler/preview-modal.test.jsx
- test/backend/QueryScheduler.spec.js
- test/backend/plotly-api.spec.js
- test/backend/routes.queries.spec.js
@nicolaskruchten @n-riesco I'm still doing some manual testing, but I wanted to get this in front of you for review since I don't foresee the crux of it changing much.
This PR makes a core change to the way grids are updated in Falcon. Because of how central an alteration this is, I'm going to go into some detail about how it's implemented to try and catch any misunderstandings or issues up front! Please let me know if any of this sounds incorrect or contrary to your understanding 🙂
Previous to this PR, the update functionality worked as follows:
- column `uid`'s are passed in as a parameter to `POST /queries`
- after running the supplied query, the `updateGrid` function is called which writes up to `uids.length` columns of data
- column names are never altered
This is problematic because …
> Rewrite grid updating functionality

- backend/persistent/QueryScheduler.js
- backend/settings.js
* Added env variable PLOTLY_CONNECTOR_BASE_URL so that it is possible to
customise connectorURL when running inside on-prem.
Closes https://github.com/plotly/streambed/issues/11310
---
@nicolaskruchten @scjody 
I've tested the PR locally:
- running as a desktop app: `yarn start`
- and simulating running inside on-prem by setting: `PLOTLY_CONNECTOR_BASE_URL="https://test/external-data-connector" PLOTLY_CONNECTOR_RUNNING_INSIDE_ON_PREM=true yarn start`
> settings: add variable PLOTLY_CONNECTOR_BASE_URL

- mock-storage/connections.yaml
- sample-storage/connections.yaml
- test/backend/datastores.impala.spec.js
Update test database connections, to switch them to instances on the main Plotly AWS account.
> Update test database connections

- backend/persistent/datastores/bigquery.js
Remove the disconnect function from bigquery.js.  This was causing an issue when deleting a tab
> Remove disconnect function.  not needed
